<?php

namespace App\Models;

use App\Scopes\DeleteAdminScope;
use App\Traits\Taggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Cache;

class BlogPost extends Model
{
    use SoftDeletes, Taggable, HasFactory;

    protected $fillable = ['title', 'content','user_id'];

    public function comments()
    {
        return $this->morphMany(Comment::class,'commentable')->latestComments();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function image()
    {
        return $this->morphOne(Image::class,'imageable');
    }

    public function scopeLatestPosts(Builder $query)
    {
        return $query->orderBy('created_at','desc');
    }

    public function scopeLatestWithRelations(Builder $query)
    {
        return $query->latestPosts()->withCount('comments')->with('user')->with('tags');
    }


    public function scopeMostCommented(Builder $query)
    {
        return $query->withCount('comments')->orderBy('comments_count','desc');
    }

    public static function boot()
    {
        static::addGlobalScope(new DeleteAdminScope);
        parent::boot(); // TODO: Change the autogenerated stub
    }


}
