<?php

namespace App\Models;

use App\Traits\Taggable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Cache;

class Comment extends Model
{
    use HasFactory;

    use SoftDeletes, Taggable;

    protected $fillable = [
        'blog_post_id',
        'user_id',
        'content'
    ];

    /**
     * Get the blog post that owns the comment.
     */
/*    public function blogPost()
    {
        return $this->belongsTo(BlogPost::class);
    }*/


    public function commentable()
    {
        $this->morphTo();
    }

    public function scopeLatestComments(Builder $query)
    {
        return $query->orderBy('created_at','desc');

    }

    public function user()
    {
        return $this->belongsTo(User::class);

    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Comment $comment){
            if($comment->commentable_type == BlogPost::class){
                Cache::tags(['blog-post'])->forget("blog-post-".$comment->commentable_id);
                Cache::tags(['blog-post'])->forget('mostCommented');
            }

        });

/*        static::addGlobalScope(new LatestScope);*/
    }
}
